name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: Ayushverma135
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set outputs
        run: |
          echo "GIF_PATH=${{ steps.snake-gif.outputs.gif_out_path }}" >> $GITHUB_OUTPUT
          echo "SVG_PATH=${{ steps.snake-gif.outputs.svg_out_path }}" >> $GITHUB_OUTPUT

      - name: Show status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GIF_PATH: ${{ steps.snake-gif.outputs.gif_out_path }}
          SVG_PATH: ${{ steps.snake-gif.outputs.svg_out_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
